os: linux

virt: lxd

jobs:
  include:
    - dist: xenial
      arch: amd64
    - dist: xenial
      arch: arm64
    - dist: xenial
      arch: ppc64le

    - dist: focal
      arch: amd64
    - dist: focal
      arch: arm64
    - dist: focal
      arch: ppc64le

script:
  - ./kill_time.sh
