os: linux

arch: amd64

jobs:
  include:
    - dist: xenial
      virt: vm
    - dist: xenial
      virt: lxd

    - dist: focal
      virt: vm
    - dist: focal
      virt: lxd

script:
  - ./kill_time.sh
